### PR TITLE
Order sections within a monograph. Story #50

### PR DESCRIPTION
**Pull request by val99erie**

### CODE REVIEW

**Comment by jmcglone** [comment]
@acozine when I run `bundle exec bin/setup` I'm seeing this deprecation warning:

`DEPRECATION WARNING: ActiveFedora::SolrQueryBuilder.solr_name is deprecated and will be removed in ActiveFedora 10.0. Use ActiveFedora.index_field_mapper.solr_name instead.`

I don't know DCE's practice and whether these kinds of things should hold up a PR, so I'll let you make the call.

**Comment by val99erie** [comment]
@jmcglone We shouldn't let the deprecation warnings hold up the PR.  They weren't introduced in this PR, and the warnings are coming from the underlying hydra gem.  There are at least 2 gems that we'll have to update before we can get rid of that message.

**Comment by jmcglone** [comment]
@val99erie Got it! Ok, another question. I've created a monograph with sections, but I can't see where to re-order the sections in the UI.

**Comment by val99erie** [comment]
Ah, Justin added the role stuff in, so the UI has changed.  There used to
be a "Manage Files" button, or something like that at the bottom of the
monograph show page.  Then you can re-order things in there.  But you might
need to make your user an admin first.  I'll try to figure out the steps
needed to do that.

Valerie

**Pull request merged**
